### ISSUE TITLE
M1下无法运行

### ISSUE THREAD

**Issue by leiyuch** [ExpLangcn/FuYao-Go#3]
![5241652238059_ pic](https://user-images.githubusercontent.com/1195803/167760496-0937f251-ead5-49f1-858e-87592418970d.jpg)

**Comment by ExpLangcn** [comment]
？你就这样截图的嘛？

**Comment by leiyuch** [comment]
> ？你就这样截图的嘛？

大神，我是在终端运行./FuYao_M1 , 就直接显示进程被杀，没其他任何错误信息抛出

**Comment by ExpLangcn** [comment]
`./FuYao_M1 -h` 执行然后截图 截全

**Comment by leiyuch** [comment]
> `./FuYao_M1 -h` 执行然后截图 截全
![5271652242572_ pic](https://user-images.githubusercontent.com/1195803/167768084-b4a0a641-8d22-4aac-b0ce-e53ba3e2bda3.jpg)
您看

**Comment by ExpLangcn** [comment]
https://blog.csdn.net/qq_41437512/article/details/123984598

**Comment by leiyuch** [comment]
> https://blog.csdn.net/qq_41437512/article/details/123984598

Reinstall了还是不行,应该是这个版本的系统bug,等更新了，谢谢您
